In [18]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine

In [25]:
Data = pd.read_csv("https://raw.githubusercontent.com/juliandnl/redi_ss20/master/berlin_rental.csv")

Username: postgres,
Password: postgres,
host: localhost,
Port: 5432,
Database: Sample

In [26]:
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/Sample')

# write to SQL by using Pandas

In [27]:
Data.to_sql('Sample_table_4',engine)

# Read to SQL by using Pandas

In [28]:
dfd=pd.read_sql('Sample_table',engine)

In [29]:
sami=[dfd,df]
sami=pd.concat(sami)

In [30]:
df[(df.Make=='Ford') & (df.Model=='Ka') & (df.Year==2012)& (df.Price>170000)]

,index,Make,Model,Year,Variant,Kms,Price,Doors,Kind,Location
368,367,Ford,Ka,2012,1.0 Fly Viral 63cv,123000,175000,3.0,Hatchback,Bs.as. G.b.a. Sur
486,486,Ford,Ka,2012,1.0 Fly Viral 63cv,42700,178200,3.0,Hatchback,Mendoza
880,880,Ford,Ka,2012,1.6 Pulse 95cv,92000,185000,3.0,Hatchback,Capital Federal
1691,1691,Ford,Ka,2012,1.6 Fly Viral 95cv,88000,180000,3.0,Hatchback,Bs.as. G.b.a. Oeste
1715,1715,Ford,Ka,2012,1.6 Pulse 95cv,62000,175000,3.0,Hatchback,Capital Federal
1758,1758,Ford,Ka,2012,1.6 Fly Viral 95cv,88000,180000,3.0,Hatchback,Bs.as. G.b.a. Oeste
2061,2060,Ford,Ka,2012,1.6 Fly Viral 95cv,40000,173000,3.0,Hatchback,Capital Federal
2818,2818,Ford,Ka,2012,1.6 Fly Viral 95cv,49000,175000,3.0,Hatchback,Córdoba
2880,2880,Ford,Ka,2012,1.0 Fly 63cv,88000,175000,3.0,Hatchback,Buenos Aires Interior
5777,5777,Ford,Ka,2012,1.6 Fly Viral 95cv,88000,180000,3.0,Hatchback,Bs.as. G.b.a. Oeste
6529,6528,Ford,Ka,2012,1.0 Fly Viral 63cv,86000,180000,3.0,Hatchback,Bs.as. G.b.a. Norte
6700,6700,Ford,Ka,2012,1.6 Pulse Top 95cv,97000,195000,3.0,Hatchback,Córdoba
7333,7333,Ford,Ka,2012,1.0 Fly Viral 63cv,60000,180000,3.0,Hatchback,Mendoza
7551,7551,Ford,Ka,2012,1.0 Fly Viral 63cv,66000,177000,3.0,Hatchback,La Rioja
8178,8178,Ford,Ka,2012,1.6 Pulse 95cv,100800,185000,3.0,Hatchback,Bs.as. G.b.a. Sur
9183,9183,Ford,Ka,2012,1.0 Fly Viral 63cv,60000,175900,3.0,Hatchback,Bs.as. G.b.a. Sur
9237,9237,Ford,Ka,2012,1.6 Pulse Top 95cv,62000,179000,3.0,Hatchback,Córdoba
9557,9557,Ford,Ka,2012,1.0 Fly Viral 63cv,40000,180000,3.0,Hatchback,Capital Federal